# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

# main:
#   - name: Bio
#     url: /
#     weight: 10
#   - name: Papers
#     url: /#papers
#     weight: 11
#   - name: Talks
#     url: /#talks
#     weight: 12
#   - name: News
#     url: /#news
#     weight: 13
#   - name: Experience
#     url: experience/
#     weight: 20
#   - name: Projects
#     url: projects/
#     weight: 30
#   - name: Teaching
#     url: teaching/
#     weight: 40

# main:
#   - name: Home
#     url: ''
#     weight: 10
#   # - name: Posts
#   #   url: '#posts'
#   #   weight: 20
#   # - name: Projects
#   #   url: '#projects'
#   #   weight: 30
#   # - name: Talks
#   #   url: '#talks'
#   #   weight: 40
#   - name: Publications
#     url: 'publication'
#     weight: 50
#   # - name: Contact
#   #   url: '#contact'
#   #   weight: 60
#   - name: News
#     url: "#news"
#     weight: 20

main:
  - name: Home
    url: "/"
    weight: 25
  - name: News
    url: "/#news"
    weight: 40
  - name: Publications
    url: "/#papers"
    weight: 40

